---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tomcat
  become_user: root
  become: yes
  vars:
    http_port: 8080
    https_port: 8443
    admin_username: admin
    admin_password: adminsecret
    tmp_dir: /home/ansible
    file_name: sample.zip
    webapps_folder: /usr/share/tomcat/webapps

  roles:
    - selinux
    - tomcat
    - deploy
